configVersion: 3060801
data:
  location: /home/zany130/.var/app/space.gaiasky.GaiaSky/data/gaiasky/data
  dataFiles:
   - $data/default-data/dataset.json
   - $data/catalog-gaia-dr3-best/dataset.json
   - $data/catalog-nbg/dataset.json
   - $data/catalog-nebulae/dataset.json
   - $data/catalog-sdss-12/dataset.json
   - $data/catalog-whitedwarfs-dr2/dataset.json
   - $data/gargantua-blackhole/dataset.json
   - $data/oort-cloud/dataset.json
   - $data/catalog-gcns/dataset.json
   - $data/catalog-asteroids-dr2/dataset.json
   - $data/catalog-asteroids-dr3-trojan/dataset.json
   - $data/catalog-asteroids-dr3-nea/dataset.json
   - $data/catalog-asteroids-dr3/dataset.json
   - $data/catalog-asteroids-fpr/dataset.json
   - $data/spacecraft-jwst/dataset.json
   - $data/spacecraft-hst/dataset.json
   - $data/spacecraft-voyagers/dataset.json
   - $data/spacecraft-iss/dataset.json
   - $data/vt-moon-topography-nasa/dataset.json
   - $data/vt-mars-topography-mola/dataset.json
   - $data/volumetric-aurora/dataset.json
   - $data/vt-earth-topography-gmted2010/dataset.json
   - $data/vt-earth-diffuse-nasa/dataset.json
   - $data/spacecraft-euclid/dataset.json
   - $data/mesh-dust-dr2/dataset.json
   - $data/mesh-hii-dr2/dataset.json
   - $data/vt-mars-diffuse-vanvliet/dataset.json
   - $data/mesh-stardensity-dr2/dataset.json
  reflectionSkyboxLocation: $data/default-data/tex/skybox/gaiasky/
  highAccuracy: false
  realGaiaAttitude: false
performance:
  multithreading: true
  numberThreads: 0
graphics:
  quality: ULTRA
  resolution:
   - 2560
   - 1080
  resizable: true
  fullScreen:
    active: true
    resolution:
     - 2560
     - 1080
    bitDepth: 24
    refreshRate: 75
  vsync: true
  fpsLimit: 0.0
  backBufferScale: 1.0
  dynamicResolution: false
  screenOutput: true
  useSRGB: false
  proceduralGenerationResolution:
   - 3000
   - 1500
scene:
  homeObject: Earth
  fadeMs: 1500
  camera:
    speed: 10.0
    turn: 1060.0
    rotate: 5000.0
    fov: 45.0
    cinematic: false
    targetMode: true
    starDistanceScaling: true
    focusLock:
      position: true
      orientation: false
    speedLimitIndex: 27
  particleGroups:
    numLabels: 0
    motionTrails: false
  star:
    renderStarSpheres: false
    brightness: 2.22
    power: 1.0
    pointSize: 3.0
    saturate: 0.16
    glowFactor: 0.075
    opacity:
     - 0.0
     - 1.0
    textureIndex: 5
    textureIndexLens: 3
    group:
      billboard: true
      numBillboard: 10
      numLabels: 10
      numVelocityVector: 50
    threshold:
      quad: 0.0
      point: 1.7E-8
      none: 0.0
  label:
    size: 1.3
    number: 1.3
  properMotion:
    length: 25000.0
    number: 5.0
    colorMode: 0
    arrowHeads: true
  octree:
    maxStars: 7000000
    threshold:
     - 1.4995868
     - 1.8995868
    fade: true
  renderer:
    ambient: 0.0
    line:
      mode: POLYLINE_QUADSTRIP
      width: 1.0
      glWidthBias: 0.0
    shadow:
      active: true
      resolution: 1024
      number: 10
    eclipses:
      active: true
      outlines: true
    elevation:
      type: TESSELLATION
      multiplier: 1.0
      quality: 4.0
    virtualTextures:
      cacheSize: 8
      detectionBufferFactor: 8.0
      maxTilesPerFrame: 8
    pointCloud: TRIANGLES
  crosshair:
    focus: true
    closest: true
    home: true
  initialization:
    lazyTexture: true
    lazyMesh: true
  visibility:
    Stars: true
    Planets: true
    Moons: true
    Satellites: true
    Asteroids: false
    Clusters: false
    MilkyWay: true
    Galaxies: true
    Nebulae: true
    Meshes: false
    Systems: true
    Labels: true
    Orbits: true
    Locations: false
    Countries: false
    Ruler: true
    Equatorial: false
    Ecliptic: false
    Galactic: false
    RecursiveGrid: false
    Constellations: false
    Boundaries: false
    Atmospheres: true
    Clouds: true
    Effects: false
    Axes: true
    VelocityVectors: false
    Keyframes: true
    Others: true
    Invisible: false
program:
  safeMode: false
  debugInfo: false
  offlineMode: false
  shaderCache: false
  saveProceduralTextures: false
  displayTimeNoUi: true
  minimap:
    active: true
    size: 200.0
    inWindow: false
  fileChooser:
    showHidden: false
    lastLocation: /home/zany130
  pointer:
    coordinates: false
    guides:
      active: false
      color:
       - 1.0
       - 1.0
       - 1.0
       - 0.3
      width: 1.5
  recursiveGrid:
    origin: REFSYS
    style: CIRCULAR
    projectionLines: true
  uvGrid:
    frameCoordinates: true
  modeStereo:
    active: false
    profile: CROSSEYE
  modeCubemap:
    active: false
    projection: EQUIRECTANGULAR
    faceResolution: 1500
    planetarium:
      aperture: 180.0
      angle: 50.0
      sphericalMirrorWarp: null
    celestialSphereIndexOfRefraction: 1.0
  net:
    restPort: -1
    master:
      active: false
      slaves: []
    slave:
      active: false
      configFile: null
      warpFile: null
      blendFile: null
      yaw: 0.0
      pitch: 0.0
      roll: 0.0
  ui:
    scale: 1.0
    animationMs: 600
    newUI: true
    expandOnMouseOver: false
    modeChangeInfo: true
    notifications: false
    theme: default
    distanceUnits: PC
  exitConfirmation: true
  locale: en-GB
  update:
    lastCheck: 2025-07-10T03:31:51.216663702Z
    lastVersion: null
  url:
    versionCheck: https://codeberg.org/api/v1/repos/gaiasky/gaiasky/tags
    dataMirror: https://gaia.ari.uni-heidelberg.de/gaiasky/files/repository/
    dataDescriptor: https://gaia.ari.uni-heidelberg.de/gaiasky/files/repository/gaiasky-data-03060501.json.gz
  timeZone: UTC
controls:
  gamepad:
    mappingsFile: /app/bin/mappings/SDL_Controller.controller
    invertX: false
    invertY: true
    blacklist: []
frame:
  location: /home/zany130/.var/app/space.gaiasky.GaiaSky/data/gaiasky/frames
  format: JPG
  quality: 0.93
  mode: SIMPLE
  resolution:
   - 1280
   - 720
  prefix: gaiasky
  time: false
  targetFps: 60.0
screenshot:
  location: /home/zany130/.var/app/space.gaiasky.GaiaSky/data/gaiasky/screenshots
  format: JPG
  quality: 0.93
  mode: SIMPLE
  resolution:
   - 1280
   - 720
camrecorder:
  targetFps: 60.0
  keyframe:
    position: CATMULL_ROM_SPLINE
    orientation: CATMULL_ROM_SPLINE
  auto: false
postprocess:
  antialiasing:
    type: NFAA
    quality: 2
  bloom:
    intensity: 2.0
    fboScale: 0.5
  unsharpMask:
    factor: 0.0
  chromaticAberration:
    amount: 0.003
  filmGrain:
    intensity: 0.0
  lensFlare:
    active: true
    type: COMPLEX
    strength: 1.0
    numGhosts: 8
    haloWidth: 0.5
    blurPasses: 35
    flareSaturation: 0.8
    bias: -0.98
    texLensColor: $data/default-data/tex/base/lenscolor.png
    texLensDirt: $data/default-data/tex/base/lensdirt%#QUAL#%.jpg
    texLensStarburst: $data/default-data/tex/base/lensstarburst.jpg
    fboScale: 0.4
  lightGlow:
    active: true
    samples: 1
  levels:
    brightness: 0.0
    contrast: 1.0
    hue: 1.0
    saturation: 1.0
    gamma: 1.0
  toneMapping:
    type: NONE
    exposure: 0.0
  ssr:
    active: false
  motionBlur:
    active: false
    strength: 0.0
  reprojection:
    active: false
    mode: DISABLED
  upscaleFilter: XBRZ
  warpingMesh:
    pfmFile: null
spacecraft:
  velocityDirection: false
  showAxes: false