LastBIOSFolder = ""
FastForwardFPS = 1000.0
PauseLostFocus = false
RecentROM = []
UITheme = ""
SlowmoFPS = 30.0
TargetFPS = 60.0
LastROMFolder = "/home/zany130/Emulation/roms/nds"
AudioSync = true
LimitFPS = true

[Instance0]
CheatFilePath = ""
JoystickID = 0
SavestatePath = "/home/zany130/Emulation/saves/melonds/states"
SaveFilePath = "/home/zany130/Emulation/saves/melonds/saves"
EnableCheats = true

[Instance0.Audio]
DSiVolumeSync = false
Volume = 256

[Instance0.Window0]
Enabled = true
ScreenFilter = false
ShowOSD = true
ScreenAspectTop = 4
IntegerScaling = false
ScreenSizing = 3
ScreenSwap = false
Geometry = "AdnQywADAAAAAAeAAAAAAAAADG0AAAQIAAAHgAAAAAAAAAxtAAAECAAAAAAAAAAACgAAAAeAAAAAAAAADG0AAAQI"
ScreenLayout = 3
ScreenGap = 0
ScreenAspectBot = 4
ScreenRotation = 0

[Instance0.Window3]
Enabled = false

[Instance0.Gdb]
Enabled = false

[Instance0.Gdb.ARM9]
BreakOnStartup = false
Port = 3333

[Instance0.Gdb.ARM7]
BreakOnStartup = false
Port = 3334

[Instance0.Window2]
Enabled = false

[Instance0.Keyboard]
HK_Reset = 16777269
HK_PowerButton = -1
HK_SwapScreenEmphasis = -1
HK_SwapScreens = 16777217
Left = -1
Y = -1
HK_FrameStep = 59
HK_SolarSensorIncrease = -1
A = -1
L = -1
R = -1
HK_GuitarGripRed = -1
HK_VolumeDown = -1
HK_GuitarGripBlue = -1
HK_Lid = 16777222
HK_SolarSensorDecrease = -1
HK_VolumeUp = -1
HK_GuitarGripGreen = -1
HK_SlowMoToggle = -1
HK_FastForwardToggle = -1
HK_GuitarGripYellow = -1
HK_FrameLimitToggle = 16777233
Up = -1
HK_FullscreenToggle = 16777274
HK_SlowMo = -1
HK_Pause = 16777238
Right = -1
Start = -1
Select = -1
X = -1
B = -1
Down = -1
HK_Mic = 45
HK_FastForward = 16777232

[Instance0.Joystick]
HK_Reset = -1
HK_PowerButton = -1
HK_SwapScreenEmphasis = -1
HK_SwapScreens = -1
Left = 264
Y = 2
HK_FrameStep = -1
HK_SolarSensorIncrease = 68288511
A = 1
L = 4
R = 5
HK_GuitarGripRed = -1
HK_VolumeDown = -1
HK_GuitarGripBlue = -1
HK_Lid = -1
HK_SolarSensorDecrease = 67239935
HK_VolumeUp = -1
HK_GuitarGripGreen = -1
HK_SlowMoToggle = -1
HK_FastForwardToggle = -1
HK_GuitarGripYellow = -1
HK_FrameLimitToggle = -1
Up = 257
HK_FullscreenToggle = -1
HK_SlowMo = -1
HK_Pause = -1
Right = 258
Start = 7
Select = 6
X = 3
B = 0
Down = 260
HK_Mic = -1
HK_FastForward = -1

[Instance0.Firmware]
MAC = ""
FavouriteColour = 12
BirthdayDay = 29
BirthdayMonth = 11
Language = 1
Username = "zany130"
Message = ""
OverrideSettings = true

[Instance0.Window1]
Enabled = false

[Instance0.DS]
[Instance0.DS.Battery]
LevelOkay = true

[Instance0.DSi]
[Instance0.DSi.Battery]
Charging = true
Level = 15

[Instance0.RTC]
Offset = -70

[Mic]
WavPath = ""
Device = "Arctis Nova 7 Mono"
InputType = 1

[Mouse]
HideSeconds = 5
Hide = true

[LAN]
Device = ""
DirectMode = false

[Audio]
BitDepth = 0
Interpolation = 0

[DS]
FirmwarePath = "/home/zany130/Emulation/bios/firmware.bin"
BIOS7Path = "/home/zany130/Emulation/bios/bios7.bin"
BIOS9Path = "/home/zany130/Emulation/bios/bios9.bin"

[Savestate]
RelocSRAM = false

[Emu]
ExternalBIOSEnable = true
DirectBoot = true
ConsoleType = 0

[MP]
RecvTimeout = 25
AudioMode = 1

[3D]
Renderer = 1

[3D.GL]
HiresCoordinates = true
BetterPolygons = true
ScaleFactor = 15

[3D.Soft]
Threaded = true

[Screen]
VSyncInterval = 1
VSync = false
UseGL = true
Filter = true

[JIT]
FastMemory = true
LiteralOptimisations = true
BranchOptimisations = true
MaxBlockSize = 32
Enable = false

[DLDI]
FolderPath = ""
FolderSync = false
ReadOnly = false
ImagePath = "dldi.bin"
ImageSize = 0
Enable = false

[DSi]
FullBIOSBoot = true
FirmwarePath = "/home/zany130/Emulation/bios/dsi_firmware.bin"
NANDPath = "/home/zany130/Emulation/bios/dsi_nand.bin"
BIOS7Path = "/home/zany130/Emulation/bios/dsi_bios7.bin"
BIOS9Path = "/home/zany130/Emulation/bios/dsi_bios9.bin"

[DSi.Camera1]
ImagePath = ""
XFlip = false
DeviceName = "/dev/video0"
InputType = 2

[DSi.Camera0]
ImagePath = ""
XFlip = false
DeviceName = "/dev/video0"
InputType = 2

[DSi.SD]
FolderPath = ""
FolderSync = false
ReadOnly = false
ImagePath = "dsisd.bin"
ImageSize = 0
Enable = false

